services:
  scraper1:
    tmpfs:
     - /tmp:size=1G,mode=1777
    build: .
    env_file: .env
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    cpu_shares: 1024
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 3G
    networks:
      - shark

  scraper2:
    tmpfs:
     - /tmp:size=1G,mode=1777
    build: .
    env_file: .env
    environment:
      PORT: 3002
    ports:
      - "3002:3002"
    cpu_shares: 1024
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 3G
    networks:
      - shark

  scraper3:
    tmpfs:
     - /tmp:size=1G,mode=1777
    build: .
    env_file: .env
    environment:
      PORT: 3003
    ports:
      - "3003:3003"
    cpu_shares: 1024
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 3G
    networks:
      - shark

  scraper4:
    tmpfs:
     - /tmp:size=1G,mode=1777
    build: .
    env_file: .env
    environment:
      PORT: 3004
    ports:
      - "3004:3004"
    cpu_shares: 1024
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 3G
    networks:
      - shark

networks:
  shark:
    external: true
